### PR TITLE
Stol repo management

### PR DESCRIPTION
**Pull request by rob-baily**
# PR Details
## Description

This embeds logic into the install_dependencies script to set up usage for the STOL repos per the discussions we have had with Kyle.  I will include some testing results in a comment or attaching a file.

## Types of changes

- [ ] Defect fix (non-breaking change that fixes an issue)
- [ ] New feature (non-breaking change that adds functionality)
- [ ] Breaking change (fix or feature that cause existing functionality to change)

## Checklist:

- [ ] I have added any new packages to the sonar-scanner.properties file
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have read the [**CONTRIBUTING**](https://github.com/usdot-fhwa-stol/carma-platform/blob/develop/Contributing.md) document.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

### CODE REVIEW

**Comment by rob-baily** [comment]
For each run below showing the run in the "install dependencies" section which sets up the repos to download from and then showing the upload in a dependent job.

****************
**Regular branch:**
https://github.com/usdot-fhwa-stol/snmp-client/actions/runs/4377798500/jobs/7661732790

```
GITHUB_REF_NAME=test_stol_repos APT_CODENAME=develop USE_DEVELOP=1
<----- List file below ----->
deb [trusted=yes] http://s3.amazonaws.com/stol-apt-repository develop main
```
https://github.com/usdot-fhwa-stol/snmp-client/actions/runs/4377798500/jobs/7661747857
```
   -- Transferring pool/ci-build/s/sn/snmp-client-1_0.0.1-20230309.git16.cd9d203_amd64.deb
```

****************
**Feature branch:**
https://github.com/usdot-fhwa-stol/snmp-client/actions/runs/4377835349/jobs/7661820525
```
GITHUB_REF_NAME=feature/test_stol_repos APT_CODENAME=feature-test-stol-repos USE_DEVELOP=1
<----- List file below ----->
deb [trusted=yes] http://s3.amazonaws.com/stol-apt-repository develop main
deb [trusted=yes] http://s3.amazonaws.com/stol-apt-repository feature-test-stol-repos main
<----- Preference file below ----->
    Package: *
    Pin: feature-test-stol-repos o=stol-apt-repository
    Pin-Priority: 999
```
https://github.com/usdot-fhwa-stol/snmp-client/actions/runs/4377835349/jobs/7661834428
```
   -- Transferring pool/feature-test-stol-repos/s/sn/snmp-client-1_0.0.1-20230309.git16.cd9d203_amd64.deb
```
****************
**Release candidate branch:**
https://github.com/usdot-fhwa-stol/snmp-client/actions/runs/4377898922/jobs/7661962382
```
GITHUB_REF_NAME=release/test_stol_repos APT_CODENAME=candidate-test-stol-repos USE_DEVELOP=0
<----- List file below ----->
deb [trusted=yes] http://s3.amazonaws.com/stol-apt-repository candidate-test-stol-repos main
<----- Preference file below ----->
    Package: *
    Pin: candidate-test-stol-repos o=stol-apt-repository
    Pin-Priority: 999
```
https://github.com/usdot-fhwa-stol/snmp-client/actions/runs/4377898922/jobs/7661975303
```
   -- Transferring pool/candidate-test-stol-repos/s/sn/snmp-client-1_0.0.1-20230309.git16.cd9d203_amd64.deb
```
****************
**Release tag:**
https://github.com/usdot-fhwa-stol/snmp-client/actions/runs/4377979925/jobs/7662140595
```
GITHUB_REF_NAME=carma-system-1.1.0 APT_CODENAME=release-carma-system-1.1.0 USE_DEVELOP=0
<----- List file below ----->
deb [trusted=yes] http://s3.amazonaws.com/stol-apt-repository release-carma-system-1.1.0 main
<----- Preference file below ----->
    Package: *
    Pin: release-carma-system-1.1.0 o=stol-apt-repository
    Pin-Priority: 999
```

https://github.com/usdot-fhwa-stol/snmp-client/actions/runs/4377979925/jobs/7662151874

```
   -- Transferring pool/release-carma-system-1.1.0/s/sn/snmp-client-1_0.0.1_amd64.deb
```
****************

**Comment by rob-baily** [comment]
Below are updated tests based on the last set of minor changes.  The release difference now is that only the feature branches use the preference file for pinning as nothing else needs to reference more than one of the logical repos.

For each run below showing the run in the "install dependencies" section which sets up the repos to download from and then showing the upload in a dependent job.

****************
**Regular branch:**
https://github.com/usdot-fhwa-stol/snmp-client/actions/runs/4385868987/jobs/7679157756

```
GITHUB_REF_NAME=test_stol_repos APT_CODENAME=develop USE_DEVELOP=1
<----- List file below ----->
deb [trusted=yes] http://s3.amazonaws.com/stol-apt-repository develop main
```
https://github.com/usdot-fhwa-stol/snmp-client/actions/runs/4385868987/jobs/7679172400
```
   -- Transferring pool/ci-build/s/sn/snmp-client-1_0.0.1-20230310.git17.ae559e2_amd64.deb
```

****************
**Feature branch:**
https://github.com/usdot-fhwa-stol/snmp-client/actions/runs/4385900644/jobs/7679230761
```
GITHUB_REF_NAME=feature/test_stol_repos APT_CODENAME=feature-test-stol-repos USE_DEVELOP=1
<----- List file below ----->
deb [trusted=yes] http://s3.amazonaws.com/stol-apt-repository develop main
deb [trusted=yes] http://s3.amazonaws.com/stol-apt-repository feature-test-stol-repos main
<----- Preference file below ----->
    Package: *
    Pin: feature-test-stol-repos o=stol-apt-repository
    Pin-Priority: 999
```
https://github.com/usdot-fhwa-stol/snmp-client/actions/runs/4385900644/jobs/7679244915
```
   -- Transferring pool/feature-test-stol-repos/s/sn/snmp-client-1_0.0.1-20230310.git17.ae559e2_amd64.deb
```
****************
**Release candidate branch:**
https://github.com/usdot-fhwa-stol/snmp-client/actions/runs/4385927525/jobs/7679289167
```
Final package list:  libsnmp-dev libspdlog-dev
GITHUB_REF_NAME=release/test_stol_repos APT_CODENAME=candidate-test-stol-repos USE_DEVELOP=0
<----- List file below ----->
deb [trusted=yes] http://s3.amazonaws.com/stol-apt-repository candidate-test-stol-repos main
```
https://github.com/usdot-fhwa-stol/snmp-client/actions/runs/4385927525/jobs/7679306289
```
   -- Transferring pool/candidate-test-stol-repos/s/sn/snmp-client-1_0.0.1-20230310.git17.ae559e2_amd64.deb
```
****************
**Release tag:**
https://github.com/usdot-fhwa-stol/snmp-client/actions/runs/4385989239/jobs/7679435706
```
GITHUB_REF_NAME=carma-system-1.1.0 APT_CODENAME=release-carma-system-1.1.0 USE_DEVELOP=0
<----- List file below ----->
deb [trusted=yes] http://s3.amazonaws.com/stol-apt-repository release-carma-system-1.1.0 main
```

https://github.com/usdot-fhwa-stol/snmp-client/actions/runs/4385989239/jobs/7679448825

```
   -- Transferring pool/release-carma-system-1.1.0/s/sn/snmp-client-1_0.0.1_amd64.deb
```
****************

**Review by codygarver — APPROVED** [review]

**Comment by rob-baily** [comment]
Set things up and for the snmp_usage client installed the package.  As you can see an older version is used for the install as it is pinned.

```
root@9c5b88249cd6:/workspaces/snmp_client_usage# apt-cache policy snmp-client-1
snmp-client-1:
  Installed: 0.0.1-20230310.git17.ae559e2
  Candidate: 0.0.1-20230310.git17.ae559e2
  Version table:
     0.0.1-20230310.git18.ad8c5d5 500
        500 http://s3.amazonaws.com/stol-apt-repository develop/main amd64 Packages
*** 0.0.1-20230310.git17.ae559e2 999
        999 http://s3.amazonaws.com/stol-apt-repository feature-test-stol-repos/main amd64 Packages
        100 /var/lib/dpkg/status
```

**Comment by rob-baily** [comment]
One last test.  Set up the snmp_client_usage to use a feature branch (feature/test_stol_repos) and can see in the install dependencies step of https://github.com/usdot-fhwa-stol/snmp-client/actions/runs/4386654219/jobs/7680979171 that is uses the pinned package:
```
Setting up snmp-client-1 (0.0.1-20230310.git17.ae559e2) 
```

Then using a regular branch (usage_test_apt_repo) and checking the install dependencies step of https://github.com/usdot-fhwa-stol/snmp-client/actions/runs/4386749067/jobs/7681196573 it is using the latest:
```
Setting up snmp-client-1 (0.0.1-20230310.git18.ad8c5d5) ...
```

**Pull request merged**
